name: Error Report
description: Report an application error or crash
title: "[Error] "
labels: ["error", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        This issue was automatically created by the error reporting system.
        
        Please review the error details below and add any additional context.

  - type: textarea
    id: error_type
    attributes:
      label: Error Type
      description: Type of error (e.g., Crash, Exception, Warning)
      value: Auto-detected
    validations:
      required: true

  - type: textarea
    id: error_message
    attributes:
      label: Error Message
      description: The error message
      value: Auto-detected
    validations:
      required: true

  - type: textarea
    id: traceback
    attributes:
      label: Traceback
      description: Error traceback (if available)
      value: Auto-detected

  - type: textarea
    id: system_info
    attributes:
      label: System Information
      description: System information (OS, version, etc.)
      value: Auto-detected

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the error (if known)
      placeholder: |
        1. 
        2. 
        3. 

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context about the error

