name: Security Vulnerability
description: Report a security vulnerability
title: "[Security] "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        **⚠️ Security Vulnerability Report**
        
        Please do not report security vulnerabilities publicly. This issue will be private and only visible to repository maintainers.
        
        If you believe you've found a security vulnerability, please provide details below.
  
  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security vulnerability
      placeholder: A clear description of the vulnerability
    validations:
      required: true
  
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the vulnerability
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true
  
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the potential impact of this vulnerability?
      placeholder: This vulnerability could allow...
    validations:
      required: true
  
  - type: textarea
    id: suggested_fix
    attributes:
      label: Suggested Fix
      description: Do you have a suggested fix?
      placeholder: I think this could be fixed by...
  
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context about the vulnerability

