import { mkdirSync, mkdtempSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { WEB_SCALE, generate, loadAppSources } from "./sync-tokens.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const generatedPath = join(here, "..", "src", "styles", "tokens.generated.css");
const appTokens = join(here, "..", "..", "desktop-electron", "renderer", "src", "tokens");

const TOKENS = `:root { --scale: 2; --unit: calc(4px * var(--scale)); --border-width: calc(2px * var(--scale)); --font-size-md: calc(14px * var(--scale)); --space-sm: calc(var(--unit) * 1.5); --radius-sm: 0; }`;
const THEME = (id, accent) => `[data-theme="${id}"] { --bg-app: #111111; --accent-primary: ${accent}; }`;

/** The declarations of the first rule in a CSS string whose selector includes `needle`. */
function block(css, needle) {
  const start = css.indexOf(needle);
  if (start < 0) return null;
  const open = css.indexOf("{", start);
  return css.slice(open + 1, css.indexOf("}", open));
}

describe("generated file", () => {
  it("equals what the app's real files give (drift fails)", () => {
    const { tokensCss, themes } = loadAppSources(appTokens);
    expect(readFileSync(generatedPath, "utf8")).toBe(generate(tokensCss, themes));
  });

  it("carries the do-not-edit header", () => {
    expect(readFileSync(generatedPath, "utf8").startsWith("/* generated by scripts/sync-tokens.mjs, do not edit")).toBe(true);
  });

  it("matches each of the app's theme colors", () => {
    const out = readFileSync(generatedPath, "utf8");
    const files = readdirSync(join(appTokens, "themes")).filter((f) => f.endsWith(".css"));
    expect(files.length).toBeGreaterThanOrEqual(5);
    for (const file of files) {
      const id = file.replace(/\.css$/, "");
      const src = readFileSync(join(appTokens, "themes", file), "utf8");
      const generatedBlock = block(out, `[data-theme="${id}"]`);
      expect(generatedBlock, id).not.toBeNull();
      const decls = [...src.matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)];
      expect(decls.length).toBeGreaterThan(20);
      for (const [, name, value] of decls) {
        expect(generatedBlock, `${id} ${name}`).toContain(`${name}: ${value.trim()};`);
      }
    }
  });

  it("falls back to Neo Dark on :root", () => {
    const out = readFileSync(generatedPath, "utf8");
    expect(out).toMatch(/:root,\s*\[data-theme="neoDark"\]\s*\{/);
  });
});

describe("generate", () => {
  it("converts scale calcs to rem at the web scale", () => {
    const out = generate(TOKENS, { neoDark: THEME("neoDark", "#8b5cf6") });
    const rem = (px) => `${Math.round(((px * WEB_SCALE) / 16) * 1e4) / 1e4}rem`;
    expect(out).toContain(`--font-size-md: ${rem(14)};`);
    expect(out).toContain(`--unit: ${rem(4)};`);
    expect(out).toContain(`--space-sm: ${rem(4 * 1.5)};`);
    expect(out).toContain("--radius-sm: 0;");
  });

  it("keeps hairline values in whole pixels", () => {
    const out = generate(TOKENS, { neoDark: THEME("neoDark", "#8b5cf6") });
    expect(out).toContain(`--border-width: ${Math.max(1, Math.floor(2 * WEB_SCALE))}px;`);
  });

  it("makes the body text land between 1rem and 1.125rem", () => {
    const rem = (14 * WEB_SCALE) / 16;
    expect(rem).toBeGreaterThanOrEqual(1);
    expect(rem).toBeLessThanOrEqual(1.125);
  });

  it("shows a token added to an input", () => {
    const out = generate(TOKENS.replace("}", "--hit-min: calc(44px * var(--scale)); }"), {});
    expect(out).toContain("--hit-min:");
  });

  it("drops a theme removed from the input", () => {
    const two = { neoDark: THEME("neoDark", "#8b5cf6"), clubNeon: THEME("clubNeon", "#ff00aa") };
    expect(generate(TOKENS, two)).toContain('[data-theme="clubNeon"]');
    expect(generate(TOKENS, { neoDark: two.neoDark })).not.toContain("clubNeon");
  });

  it("does not throw on round(), max(), min(), clamp() and @property", () => {
    const css = `
      @property --row-height { syntax: "<length>"; inherits: true; initial-value: calc(28px * var(--scale)); }
      :root {
        --scale: 2;
        --a: round(calc(1.5 * 10px * var(--scale)), 4px);
        --b: max(calc(1px * var(--scale)), 1px);
        --c: min(10px, var(--unknown));
        --d: clamp(1px, var(--x), calc(2px * var(--scale)));
        --e: round(up, var(--unknown), 3px);
        --f: calc(((((;
      }`;
    let out = "";
    expect(() => {
      out = generate(css, { neoDark: THEME("neoDark", "#8b5cf6") });
    }).not.toThrow();
    // computable ones are resolved to a length, not left as functions
    expect(out).toMatch(/--a: [\d.]+rem;/);
    expect(out).toMatch(/--b: \d+px;|--b: [\d.]+rem;/);
    expect(out).toMatch(/--row-height: [\d.]+rem;/);
    expect(out).not.toContain("@property");
    // non-scale references pass through unchanged
    expect(out).toContain("--c: min(10px, var(--unknown));");
  });
});

describe("PAGES-14 tokens", () => {
  // the exact expressions of docs/v1/PHASE14_PAGES.md
  const PAGES14 = `
    @property --row-height { syntax: "<length>"; inherits: true; initial-value: 36px; }
    :root {
      --scale: 1.5;
      --hit-min: calc(44px * var(--scale));
      --hairline: max(1px, round(down, calc(1px * var(--scale)), 1px));
      --row-height: round(nearest, calc(var(--hit-min) * 0.75), 1px);
      --shadow-bevel-sm: inset var(--hairline) var(--hairline) 0 #fff;
    }`;
  const out = generate(PAGES14, { neoDark: THEME("neoDark", "#8b5cf6") });

  it("resolves --hairline to 1px at the web scale (rounded down, like Chromium)", () => {
    expect(out).toContain("--hairline: 1px;");
  });

  it("brings the @property --row-height through as a plain custom property", () => {
    // 44 * 1.25 = 55px, * 0.75 = 41.25px, nearest whole pixel = 41px
    expect(out).toContain(`--row-height: ${41 / 16}rem;`);
    expect(out).not.toContain("@property");
  });

  it("emits the structural block for :root and every [data-theme]", () => {
    expect(out).toMatch(/^:root,\n\[data-theme\] \{/m);
  });
});

describe("generate edge cases", () => {
  it("passes em values through untouched", () => {
    const out = generate(":root { --scale: 2; --x: calc(2em * var(--scale)); }", {});
    expect(out).toContain("--x: calc(2em * var(--scale));");
  });

  it("throws when a theme file's selector does not match its name", () => {
    expect(() => generate(TOKENS, { neoDark: THEME("other", "#fff") })).toThrow(/neoDark/);
  });

  it("reads :root and @property from every css file, skipping selector rules", () => {
    const dir = mkdtempSync(join(tmpdir(), "tokens-"));
    mkdirSync(join(dir, "themes"));
    writeFileSync(join(dir, "tokens.css"), ":root { --a: 1px; }");
    writeFileSync(join(dir, "layout.css"), "#root { --not-a-token: 1px; }\n:root { --b: 2px; }");
    const { tokensCss } = loadAppSources(dir);
    const out = generate(tokensCss, {});
    expect(out).toContain("--b:");
    expect(out).not.toContain("--not-a-token");
  });
});
