#!/usr/bin/env node
/**
 * Brings the app's design tokens to the web (SITE-02).
 *
 * Reads the renderer's `tokens.css` (:root) and `themes/*.css` ([data-theme="<id>"]) and writes
 * `src/styles/tokens.generated.css` with the app's `--scale` fixed for the web:
 *
 *  - `calc(Npx * var(--scale))` and nested calcs, `round()`, `max()`, `min()`, `clamp()` and
 *    `@property` initial values are resolved numerically at WEB_SCALE where they are computable;
 *    anything that references a non-scale variable passes through unchanged.
 *  - sizes become `rem` (px / 16, 4 decimals) so the visitor's text size is honored;
 *  - hairline tokens (border widths, bevels, the focus ring, shadow offsets) stay in whole
 *    `px` (rounded down, as Chromium rounds borders), never below 1px, so outlines stay crisp;
 *  - colors and every other value are copied as they are.
 *
 * `generate()` is pure (the tests call it); the CLI below reads the app's files and writes the result.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

/**
 * The app draws at `--scale: 2` (a pixel grid of 2 screen pixels per cell). The web fixes it at
 * 1.25, so `--font-size-md` (14px) lands at 17.5px = 1.09375rem: inside the 1rem to 1.125rem
 * range for body text. Documented in apps/website/PRODUCT.md.
 */
export const WEB_SCALE = 1.25;

/** The theme that `:root` falls back to (DEC-190). */
export const DEFAULT_THEME = "neoDark";

const HEADER = "/* generated by scripts/sync-tokens.mjs, do not edit */\n";

/** Tokens whose lengths stay in whole px: border widths, bevels, the focus ring, shadows. */
const HAIRLINE = /^--(border-width|bevel|focus-ring|shadow|hairline)/;

// ---------------------------------------------------------------------------------------------
// CSS reading (small, forgiving: bad input is passed through, never thrown on)

function stripComments(css) {
  return css.replace(/\/\*[\s\S]*?\*\//g, "");
}

/** Index of the `}` that closes the `{` at `open`, or -1. */
function matchBrace(css, open) {
  let depth = 0;
  for (let i = open; i < css.length; i++) {
    if (css[i] === "{") depth++;
    else if (css[i] === "}" && --depth === 0) return i;
  }
  return -1;
}

/** Top-level rules as { selector, body }. At-rules with blocks come out with their prelude as selector. */
function topLevelRules(css) {
  const rules = [];
  let i = 0;
  while (i < css.length) {
    const open = css.indexOf("{", i);
    if (open < 0) break;
    const close = matchBrace(css, open);
    if (close < 0) break;
    const prelude = css.slice(i, open);
    // an earlier `;`-ended statement (e.g. @import) belongs to no rule
    const selector = prelude.slice(prelude.lastIndexOf(";") + 1).trim();
    rules.push({ selector, body: css.slice(open + 1, close) });
    i = close + 1;
  }
  return rules;
}

/** Splits on `sep` at paren depth 0. */
function splitTop(text, sep) {
  const parts = [];
  let depth = 0;
  let start = 0;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (ch === "(") depth++;
    else if (ch === ")") depth = Math.max(0, depth - 1);
    else if (ch === sep && depth === 0) {
      parts.push(text.slice(start, i));
      start = i + 1;
    }
  }
  parts.push(text.slice(start));
  return parts;
}

/** Custom-property declarations of a rule body, in order: [name, value][]. */
function declarations(body) {
  const out = [];
  for (const part of splitTop(body, ";")) {
    const colon = part.indexOf(":");
    if (colon < 0) continue;
    const name = part.slice(0, colon).trim();
    if (!name.startsWith("--")) continue;
    const value = part.slice(colon + 1).replace(/\s+/g, " ").trim();
    if (value) out.push([name, value]);
  }
  return out;
}

// ---------------------------------------------------------------------------------------------
// Numeric resolution. A quantity is { n, len } where len is true for a length (stored in px).

const NUM = /^[+-]?(\d+\.?\d*|\.\d+)(e[+-]?\d+)?/i;

function parseQuantity(token) {
  const m = NUM.exec(token);
  if (!m) return null;
  const rest = token.slice(m[0].length).toLowerCase();
  const n = parseFloat(m[0]);
  if (rest === "") return { n, len: false };
  if (rest === "px") return { n, len: true };
  if (rest === "rem") return { n: n * 16, len: true };
  return null; // em (depends on the element), %, vw, deg ...: not computable here
}

/**
 * Evaluates an expression (the inside of calc(), or a bare operand list). `lookup(name)` gives a
 * quantity for a var() or null. Returns a quantity or null when not computable.
 */
function evaluate(expr, lookup) {
  const src = expr.trim();
  let pos = 0;

  const peek = () => src[pos];
  const ws = () => {
    while (pos < src.length && /\s/.test(src[pos])) pos++;
  };

  function readArgs() {
    // after "(" : read comma separated sub-expressions up to the matching ")"
    const args = [];
    let depth = 0;
    let start = pos;
    for (; pos < src.length; pos++) {
      const ch = src[pos];
      if (ch === "(") depth++;
      else if (ch === ")") {
        if (depth === 0) {
          args.push(src.slice(start, pos));
          pos++;
          return args;
        }
        depth--;
      } else if (ch === "," && depth === 0) {
        args.push(src.slice(start, pos));
        start = pos + 1;
      }
    }
    return null;
  }

  function same(a, b) {
    return a.len === b.len;
  }

  function call(name, args) {
    const strategies = ["nearest", "up", "down", "to-zero"];
    if (name === "calc" || name === "") {
      if (args.length !== 1) return null;
      return evaluate(args[0], lookup);
    }
    if (name === "var") {
      return lookup(args[0].trim());
    }
    if (name === "round") {
      let strategy = "nearest";
      let rest = args;
      if (strategies.includes(args[0].trim())) {
        strategy = args[0].trim();
        rest = args.slice(1);
      }
      if (rest.length < 1 || rest.length > 2) return null;
      const a = evaluate(rest[0], lookup);
      const b = rest.length === 2 ? evaluate(rest[1], lookup) : { n: 1, len: false };
      if (!a || !b || !same(a, b) || b.n === 0) return null;
      const q = a.n / b.n;
      const r =
        strategy === "up" ? Math.ceil(q) : strategy === "down" ? Math.floor(q) : strategy === "to-zero" ? Math.trunc(q) : Math.round(q);
      return { n: r * b.n, len: a.len };
    }
    if (name === "max" || name === "min") {
      const qs = args.map((a) => evaluate(a, lookup));
      if (qs.length < 1 || qs.some((q) => !q) || qs.some((q) => !same(q, qs[0]))) return null;
      const ns = qs.map((q) => q.n);
      return { n: name === "max" ? Math.max(...ns) : Math.min(...ns), len: qs[0].len };
    }
    if (name === "clamp") {
      if (args.length !== 3) return null;
      const [lo, v, hi] = args.map((a) => evaluate(a, lookup));
      if (!lo || !v || !hi || !same(lo, v) || !same(v, hi)) return null;
      return { n: Math.min(Math.max(v.n, lo.n), Math.max(lo.n, hi.n)), len: v.len };
    }
    return null;
  }

  function primary() {
    ws();
    const ch = peek();
    if (ch === undefined) return null;
    if (ch === "(") {
      pos++;
      const args = readArgs();
      return args && args.length === 1 ? evaluate(args[0], lookup) : null;
    }
    const ident = /^[a-z-]+(?=\()/i.exec(src.slice(pos));
    if (ident) {
      pos += ident[0].length + 1;
      const args = readArgs();
      return args ? call(ident[0].toLowerCase(), args) : null;
    }
    const m = /^[+-]?(\d+\.?\d*|\.\d+)(e[+-]?\d+)?[a-z%]*/i.exec(src.slice(pos));
    if (!m) return null;
    pos += m[0].length;
    return parseQuantity(m[0]);
  }

  function unary() {
    ws();
    if (peek() === "-" && /\s/.test(src[pos + 1] ?? "") === false && !NUM.test(src.slice(pos))) {
      pos++;
      const q = primary();
      return q && { n: -q.n, len: q.len };
    }
    return primary();
  }

  function term() {
    let left = unary();
    for (;;) {
      ws();
      const op = peek();
      if (op !== "*" && op !== "/") return left;
      pos++;
      const right = unary();
      if (!left || !right) return null;
      if (op === "*") {
        if (left.len && right.len) return null;
        left = { n: left.n * right.n, len: left.len || right.len };
      } else {
        if (right.len || right.n === 0) return null;
        left = { n: left.n / right.n, len: left.len };
      }
    }
  }

  function sum() {
    let left = term();
    for (;;) {
      ws();
      const op = peek();
      if (op !== "+" && op !== "-") return left;
      pos++;
      const right = term();
      if (!left || !right || !same(left, right)) return null;
      left = { n: op === "+" ? left.n + right.n : left.n - right.n, len: left.len };
    }
  }

  try {
    const result = sum();
    ws();
    return pos === src.length ? result : null;
  } catch {
    return null;
  }
}

const round4 = (x) => Math.round(x * 1e4) / 1e4;

function formatLength(px, hairline) {
  if (px === 0) return "0";
  if (hairline) {
    const snapped = Math.max(1, Math.floor(Math.abs(px)));
    return `${px < 0 ? "-" : ""}${snapped}px`;
  }
  return `${round4(px / 16)}rem`;
}

const MATH_FN = /\b(calc|round|max|min|clamp)\(/gi;

/**
 * Replaces each computable math function in a value with its length. A function that can't be
 * computed (it reads a non-scale variable, or is malformed) is left exactly as written.
 */
function resolveValue(value, lookup, hairline) {
  let out = "";
  let i = 0;
  MATH_FN.lastIndex = 0;
  while (i < value.length) {
    MATH_FN.lastIndex = i;
    const m = MATH_FN.exec(value);
    if (!m) break;
    const start = m.index;
    // find matching paren
    let depth = 0;
    let end = -1;
    for (let j = start + m[0].length - 1; j < value.length; j++) {
      if (value[j] === "(") depth++;
      else if (value[j] === ")" && --depth === 0) {
        end = j;
        break;
      }
    }
    if (end < 0) break; // unbalanced: pass the rest through
    const text = value.slice(start, end + 1);
    const q = evaluate(text, lookup);
    out += value.slice(i, start);
    out += q ? (q.len ? formatLength(q.n, hairline) : String(round4(q.n))) : text;
    i = end + 1;
  }
  return out + value.slice(i);
}

// ---------------------------------------------------------------------------------------------

function parseTokens(tokensCss) {
  const css = stripComments(tokensCss);
  const entries = new Map();
  const props = [];
  for (const rule of topLevelRules(css)) {
    if (rule.selector === ":root") {
      for (const [name, value] of declarations(rule.body)) entries.set(name, value);
    } else if (/^@property\s+(--[\w-]+)$/.test(rule.selector)) {
      const name = rule.selector.split(/\s+/)[1];
      const initial = /initial-value\s*:\s*([^;]+)/.exec(rule.body);
      if (initial) props.push([name, initial[1].replace(/\s+/g, " ").trim()]);
    }
  }
  // an @property initial value is a default: the :root declaration wins
  for (const [name, value] of props) if (!entries.has(name)) entries.set(name, value);
  return entries;
}

function parseTheme(id, css) {
  const rules = topLevelRules(stripComments(css));
  const own = rules.find((r) => r.selector.includes(`[data-theme="${id}"]`));
  if (!own) throw new Error(`sync-tokens: themes/${id}.css has no [data-theme="${id}"] rule (its selector must match its file name)`);
  return declarations(own.body);
}

function resolveAll(entries) {
  const resolved = new Map();
  const cache = new Map(); // name -> quantity | null
  const visiting = new Set();

  function quantityOf(name) {
    if (name === "--scale") return { n: WEB_SCALE, len: false };
    if (cache.has(name)) return cache.get(name);
    if (visiting.has(name) || !entries.has(name)) return null;
    visiting.add(name);
    const text = resolveToText(name);
    visiting.delete(name);
    // a var() reference is only inlined when it is a plain number or length
    const q = text === "0" ? { n: 0, len: true } : parseQuantity(text);
    cache.set(name, q);
    return q;
  }

  function resolveToText(name) {
    if (resolved.has(name)) return resolved.get(name);
    const value = entries.get(name);
    let text = value;
    try {
      const hairline = HAIRLINE.test(name);
      text = resolveValue(value, (arg) => quantityOf(arg), hairline);
    } catch {
      text = value;
    }
    resolved.set(name, text);
    return text;
  }

  for (const name of entries.keys()) resolveToText(name);
  return resolved;
}

function block(selector, pairs) {
  const lines = pairs.map(([name, value]) => `  ${name}: ${value};`);
  return `${selector} {\n${lines.join("\n")}\n}\n`;
}

/**
 * Pure: the app's tokens.css text and a { themeId: css text } map in, the generated CSS out.
 */
export function generate(tokensCss, themes) {
  const entries = parseTokens(tokensCss);
  // `--scale` is fixed for the web, whatever the app declares
  entries.set("--scale", String(WEB_SCALE));
  const resolved = resolveAll(entries);
  const structural = [...resolved.entries()];

  // theme values go through the same resolver, with the structural tokens in scope
  const themeBlocks = Object.entries(themes).map(([id, css]) => {
    const own = new Map(entries);
    const decls = parseTheme(id, css);
    for (const [name, value] of decls) own.set(name, value);
    const all = resolveAll(own);
    return [id, decls.map(([name]) => [name, all.get(name)])];
  });

  let out = HEADER;
  out += `/* Web scale ${WEB_SCALE}: sizes in rem, hairlines in whole px. */\n`;
  // `[data-theme]` too, so composite tokens (shadows, bevels) re-resolve inside nested theme blocks
  out += block(":root,\n[data-theme]", structural);
  const fallbackId = themeBlocks.find(([id]) => id === DEFAULT_THEME)?.[0] ?? themeBlocks[0]?.[0];
  const ordered = [
    ...themeBlocks.filter(([id]) => id === fallbackId),
    ...themeBlocks.filter(([id]) => id !== fallbackId),
  ];
  for (const [id, pairs] of ordered) {
    const selector = id === fallbackId ? `:root,\n[data-theme="${id}"]` : `[data-theme="${id}"]`;
    out += `\n${block(selector, pairs)}`;
  }
  return out;
}

/**
 * Reads the app's token sources from its tokens directory: every *.css beside the themes folder
 * (tokens.css first, then layout.css and any others). Only their `:root` and `@property` rules count;
 * selector rules (e.g. layout.css's `#root`) are ignored by the parser.
 */
export function loadAppSources(tokensDir) {
  const names = readdirSync(tokensDir)
    .filter((f) => f.endsWith(".css"))
    .sort((a, b) => (a === "tokens.css" ? -1 : b === "tokens.css" ? 1 : a.localeCompare(b)));
  const tokensCss = names.map((f) => readFileSync(join(tokensDir, f), "utf8")).join("\n");
  const themes = {};
  const files = readdirSync(join(tokensDir, "themes"))
    .filter((f) => f.endsWith(".css"))
    .sort();
  for (const file of files) {
    themes[file.replace(/\.css$/, "")] = readFileSync(join(tokensDir, "themes", file), "utf8");
  }
  return { tokensCss, themes };
}

function main() {
  const here = dirname(fileURLToPath(import.meta.url));
  const tokensDir = join(here, "..", "..", "desktop-electron", "renderer", "src", "tokens");
  const target = join(here, "..", "src", "styles", "tokens.generated.css");
  const { tokensCss, themes } = loadAppSources(tokensDir);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, generate(tokensCss, themes));
  console.log(`sync-tokens: wrote ${target}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
